# 忽略鉴权url，即设置为anon的url
ignored:
  urls:
    - /admin/login
    - /admin/getLogin
    - /admin/register
    - /admin/getRegister
    - /admin/forget
    - /admin/getForget
#redis
redis:
  #redis机器ip
  host: 127.0.0.1
  #redis端口
  port: 6379
  #redis密码
  password: 123456
  #默认数据库
  database: 10
  #redis超时时间（毫秒），如果不设置，取默认值2000
  timeout: 10000